on: [push]

jobs:
  local_development:
    runs-on: ubuntu-latest
    name: Testing action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create timestamped file
        run: date --iso-8601=seconds | tee sample/date.txt
      - name: Upload files
        uses: ./ # Uses an action in the root directory
        with:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          DROPBOX_DESTINATION_PATH_PREFIX: "/"
          GLOB: "sample/**/*.md"
          FILE_WRITE_MODE: overwrite
      - name: Upload sample artifact
        uses: actions/upload-artifact@v2
        with:
          name: sample
          path: sample/
